export const rows = [
    {
        id: 1,
        userName: "Snow",
        designation: "Hiring",
        department: "HR",
        phone: "1232344359",
    },
    {
        id: 2,
        userName: "Lannister",
        designation: "MERN stack intern",
        department: "Technial",
        phone: "2345335323",
    },
    {
        id: 3,
        userName: "Lannister",
        designation: "Editor",
        department: "Creative",
        phone: "7584936283",
    },
    {
        id: 4,
        userName: "Stark",
        designation: "Learning",
        department: "L&D",
        phone: "7463282623",
    },
    {
        id: 5,
        userName: "Targaryen",
        designation: "Teacher",
        department: "Classroom",
        phone: null,
    },
    {
        id: 6,
        userName: "Melisandre",
        designation: "Officer",
        department: "OGD",
        phone: "8472556498",
    },
    {
        id: 7,
        userName: "Clifford",
        designation: "Recrutment",
        department: "HR",
        phone: "9876654342",
    },
    {
        id: 8,
        userName: "Frances",
        designation: "Development",
        department: "L&D",
        phone: "94387293",
    },
    {
        id: 9,
        userName: "Roxie",
        designation: "Helper",
        department: "OGA",
        phone: "7856341267",
    },
];
